### ISSUE TITLE
Errors upon Mavericks installation of JSSImporter

### ISSUE THREAD

**Issue by homebysix** [sheagcraig/JSSImporter#20]
Upon manually installing JSSImporter-0.3.5.pkg on a Mavericks Mac and then running any `.jss` autopkg recipe, I'm getting this error:
```
JSSImporter: Requires python-jss version: 0.5.3. Installed: 0.3.11
```

So I tried manually removing the JSSImporter (and old jss-autopkg-addon) components and reinstalling, and I get these errors from the installer log:
```
Dec 30 10:23:52 hostname.local installd[2287]: PackageKit: ----- Begin install -----
Dec 30 10:23:52 hostname.local installd[2287]: PackageKit: request=PKInstallRequest <1 packages, destination=/>
Dec 30 10:23:52 hostname.local installd[2287]: PackageKit: packages=(
        "PKLeopardPackage <file://localhost/Users/it/Downloads/JSSImporter-0.3.5.pkg>"
    )
Dec 30 10:23:52 hostname.local installd[2287]: PackageKit: Will do receipt-based obsoleting for package identifier com.github.sheagcraig.jssimporter (prefix path=)
Dec 30 10:23:52 hostname.local installd[2287]: PackageKit: Extracting file://localhost/Users/it/Downloads/JSSImporter-0.3.5.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/F8AC67D4-4C8C-43A7-91E8-7FBE31AE7649.activeSandbox/Root, uid=0)
Dec 30 10:23:52 hostname.local installd[2287]: PackageKit: prevent user idle system sleep
Dec 30 10:23:52 hostname.local installd[2287]: PackageKit: suspending backupd
Dec 30 10:23:52 hostname.local installd[2287]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/F8AC67D4-4C8C-43A7-91E8-7FBE31AE7649.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/F8AC67D4-4C8C-43A7-91E8-7FBE31AE7649.activeSandbox
Dec 30 10:23:52 hostname.local installd[2287]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/F8AC67D4-4C8C-43A7-91E8-7FBE31AE7649.activeSandbox/Root (2 items) to /
Dec 30 10:23:52 hostname.local install_monitor[31835]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Dec 30 10:23:52 hostname.local installd[2287]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.jlpLdh/Scripts/com.github.sheagcraig.jssimporter.12RDGD
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall: Traceback (most recent call last):
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:   File "/usr/bin/easy_install-2.7", line 7, in <module>
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:     from pkg_resources import load_entry_point
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:   File "/Library/Python/2.7/site-packages/pkg_resources.py", line 2880, in <module>
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:     working_set = WorkingSet._build_master()
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:   File "/Library/Python/2.7/site-packages/pkg_resources.py", line 434, in _build_master
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:     return cls._build_from_requirements(__requires__)
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:   File "/Library/Python/2.7/site-packages/pkg_resources.py", line 447, in _build_from_requirements
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:     dists = ws.resolve(reqs, Environment())
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:   File "/Library/Python/2.7/site-packages/pkg_resources.py", line 626, in resolve
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:     raise DistributionNotFound(req)
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall: pkg_resources.DistributionNotFound: setuptools==0.6c12dev-r88846
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall: Traceback (most recent call last):
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:   File "/usr/bin/easy_install-2.7", line 7, in <module>
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:     from pkg_resources import load_entry_point
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:   File "/Library/Python/2.7/site-packages/pkg_resources.py", line 2880, in <module>
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:     working_set = WorkingSet._build_master()
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:   File "/Library/Python/2.7/site-packages/pkg_resources.py", line 434, in _build_master
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:     return cls._build_from_requirements(__requires__)
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:   File "/Library/Python/2.7/site-packages/pkg_resources.py", line 447, in _build_from_requirements
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:     dists = ws.resolve(reqs, Environment())
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:   File "/Library/Python/2.7/site-packages/pkg_resources.py", line 626, in resolve
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall:     raise DistributionNotFound(req)
Dec 30 10:23:53 hostname.local installd[2287]: ./postinstall: pkg_resources.DistributionNotFound: setuptools==0.6c12dev-r88846
Dec 30 10:23:53 hostname.local installd[2287]: PackageKit: Writing receipt for com.github.sheagcraig.jssimporter to /private/var/db/receipts
Dec 30 10:23:53 hostname.local installd[2287]: Installed "JSSImporter-0.3.5" ()
Dec 30 10:23:53 hostname.local install_monitor[31835]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Dec 30 10:23:53 hostname.local installd[2287]: PackageKit: releasing backupd
Dec 30 10:23:53 hostname.local installd[2287]: PackageKit: allow user idle system sleep
Dec 30 10:23:53 hostname.local installd[2287]: PackageKit: ----- End install -----
```

I don't get the above installation errors on a Yosemite Mac, so I suspect it's OS-dependent.

**Comment by sheagcraig** [comment]
It looks like that system doesn't have the setuptools package installed, which is weird. I just ssh'ed into a lab machine with Mavericks and it installed just fine.

I then tried a "git" in the terminal as a quick way to see if the machine even had the command line developer tools, and it *didn't*, which was my initial guess.

Then I thought, let me look at a *really*-developer-free machine in our lower school (our US computers sometimes have things like pygame installed, which may set up other packages; not sure.) It worked cleanly on there too.

So I started digging in more. Looking at the python packaging code is way overwhelming... My clean mavericks machines do NOT have the same version of pkg_resources.py that you have. Line 626, which is the exception raiser at the end of the chain above is a blank line in mine. So I searched and found the relevant section.

This "resolve" method looks for distributions required as part of a "requirement". I have not specified any requirements in the python-jss setup.py, but I imagine since it's failing on requiring setuptools 0.6c12dev-r88846 that *something* in the toolchain thinks that it needs it. Looking at which version of setuptools is on my lower school machines by "default", they have 0.6c12dev-r88846. So something in either my build adds that in, or something in your build *doesn't* add that in.

Do you have a clean Mavericks install you can test on?

**Comment by sheagcraig** [comment]
Any update on this issue @homebysix ?

**Comment by homebysix** [comment]
Just tried again with 0.3.6 and it looks like the issue is resolved! Thanks.
