### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by jameslbrown** [sheagcraig/JSSImporter#67]
Recipe eg: com.github.jss-recipes.jss.Office2011Update
Gives error message:
Error in com.github.jss-recipes.jss.Office2011Update: Processor: JSSImporter: Error: [Errno 2] No such file or directory: u'/Volumes/CasperShare-1/Packages/Office 2011 14.5.7 Update.kg'

Traceback:
Traceback (most recent call last): File "/usr/local/bin/autopkg", line 1459, in run_recipes autopackager.process(recipe) File "/Library/AutoPkg/autopkglib/__init__.py", line 479, in process % (identifier, step["Processor"], unicode(err))) AutoPackagerError: Error in com.github.jss-recipes.jss.Office2011Update: Processor: JSSImporter: Error: [Errno 2] No such file or directory: u'/Volumes/CasperShare-1/Packages/Office 2011 14.5.7 Update.pkg'

The Casper share is on a Drobo 5N NAS. In JSSImporter Integration section I get a green dot when I click on Connect.

Looks like it is putting a 'u' in front of the path. 

Same happens with com.github.jss-recipes.jss.AdobeFlashPlayer recipe.

Any ideas what is happening or how to fix?

Thanks,

James.

PS, running El Cap 10.11.1, Casper 9.8.1, AutoPkgr 0.5.1

**Comment by jameslbrown** [comment]
Any progress on this sheagcraig?

**Comment by sheagcraig** [comment]
I would need a lot more information to know what is going on. Can you wrap the traceback in the markdown code blocks and post a sanitized AutoPkg prefs. I can't comment on the validation that AutoPkgr does for the distribution point; is it actually mounted at /Volumes/CasperShare-1 when you run this recipe?

The "u" just means that it is a unicode string.

**Comment by sheagcraig** [comment]
Any updates on this?

**Comment by sheagcraig** [comment]
Closing after no response.
